# TODO
# .github/workflows/test_action.yml
name: Export PDF
on: 
  push:
  #workflow_dispatch:

jobs:
  test-export-scibus-pdf:
    runs-on: ubuntu-latest
    name: Test the Export Scribus PDF action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export Scribus PDF
        id: export-scribus-pdf
        uses: ./ # Uses an action in the root directory
        with:
          sla-file: 'PonovoVodic.sla'
      - name: Print result
        run: echo "${{ steps.export-scribus-pdf.outputs.pdf-file }}"
